#
# Starts DevPortal with hot reloading and pretty logging:
#
# docker compose up --no-log-prefix | npx --yes pino-pretty --colorize --translateTime
#
# Changes to dynamic-plugins*.yaml will be processed into app-config running this:
#
# docker compose exec devportal /app/install-dynamic-plugins.sh /app/dynamic-plugins-root
#

services:
  devportal:
    image: veecode/devportal:1.2.1
    ports:
      - "7007:7007"
    environment:
      - DEVELOPMENT=true
      # will use shell value
      - GITHUB_ORG
      - GITHUB_APP_ID
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_PRIVATE_KEY
      - GITHUB_TOKEN
    volumes:
      # your config will add/override the default image config
      - ./app-config.yaml:/app/app-config.local.yaml:ro
      # dynamic plugins config (just enable/disable plugins)
      - ./dynamic-plugins.yaml:/app/dynamic-plugins.yaml:ro
      # default dynamic plugins config (with default values)
      # - ./dynamic-plugins.default.yaml:/app/dynamic-plugins.default.yaml:ro

