name: Docker Build and Test

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'

env:
  IMAGE_NAME: veecode/devportal

permissions:
  contents: read
  
jobs:

  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Ensure tag exists in main
        run: |
          git fetch origin main
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Pushed TAG=$TAG"
          SHA="$(git rev-parse "$TAG^{commit}")"
          if git merge-base --is-ancestor "$SHA" origin/main; then
            echo "OK: tag commit is reachable from main."
          else
            echo "ERROR: tag commit is not on main." >&2
            exit 1
          fi

  build:
    needs: validate-tag
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            arch: amd64
          - os: ubuntu-22.04-arm
            platform: linux/arm64
            arch: arm64
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract tag version
      id: extract-tag
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Extracted TAG=$TAG"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build image (with cache)
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ matrix.platform }}
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.extract-tag.outputs.tag }}-${{ matrix.arch }}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Extract tag version
        id: extract-tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Extracted TAG=$TAG"
  
      # login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create multi-arch manifest (SHA tag)
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ steps.extract-tag.outputs.tag }} \
            ${{ env.IMAGE_NAME }}:${{ steps.extract-tag.outputs.tag }}-amd64 \
            ${{ env.IMAGE_NAME }}:${{ steps.extract-tag.outputs.tag }}-arm64
