name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: devportal-distro
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:test .
    
    - name: Test Docker image
      run: |
        # Test that the image was built successfully
        docker images | grep ${{ env.IMAGE_NAME }}
        
        # Test that we can inspect the image
        docker inspect ${{ env.IMAGE_NAME }}:test
        
        echo "Docker image built successfully!"
    
    - name: Check installed plugins
      run: |
        # Check if any plugins were installed
        docker run --rm ${{ env.IMAGE_NAME }}:test ls -la /opt/app-root/src/dynamic-plugins-root/ || echo "No plugins installed (expected if dynamic-plugins.yaml is empty)"
